# Generated by Django 6.0.3 on 2026-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=255)),
                ('display_phone_number', models.CharField(max_length=255)),
                ('profile_name', models.CharField(max_length=255)),
                ('wa_id', models.CharField(max_length=255, unique=True)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
