# Generated by Django 6.0.3 on 2026-03-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('messaging_product', models.CharField(max_length=100)),
                ('messages', models.JSONField()),
                ('from_number', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.contactwhatsapp')),
            ],
        ),
    ]
