# Generated by Django 6.0.3 on 2026-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_phone_number', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
