# Generated by Django 6.0.3 on 2026-03-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_whatsappnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.whatsappnumber'),
        ),
    ]
