# Generated by Django 6.0.3 on 2026-03-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_whatsappmessage_from_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundWhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.CharField(max_length=255, unique=True)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou')], default='sent', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='crm.contactwhatsapp')),
                ('from_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='crm.whatsappnumber')),
            ],
        ),
    ]
