# Generated by Django 6.0.3 on 2026-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_outboundwhatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactwhatsapp',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
