# Generated by Django 6.0.3 on 2026-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_contactwhatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundwhatsappmessage',
            name='message_text',
        ),
        migrations.AddField(
            model_name='outboundwhatsappmessage',
            name='message',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
