# Generated by Django 6.0.3 on 2026-03-18 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_outboundwhatsappmessage_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
