# Generated by Django 6.0.3 on 2026-03-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_whatsappmessage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactwhatsapp',
            name='display_phone_number',
        ),
        migrations.RemoveField(
            model_name='contactwhatsapp',
            name='phone_number_id',
        ),
    ]
