# Generated by Django 6.0.3 on 2026-03-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_contactwhatsapp_display_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='crm.contactwhatsapp')),
                ('from_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='crm.whatsappnumber')),
            ],
        ),
    ]
