# Generated by Django 6.0.3 on 2026-03-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundwhatsappmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='crm.chat'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='crm.chat'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('contact', 'from_number')},
        ),
    ]
