# Generated by Django 6.0.3 on 2026-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_outboundwhatsappmessage_chat_whatsappmessage_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnumber',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
