# Generated by Django 6.0.3 on 2026-04-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_whatsappnumber_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('header', 'Header'), ('body', 'Body'), ('footer', 'Footer'), ('buttons', 'Buttons')], max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('header_format', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20, null=True)),
                ('example_media_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('marketing', 'Marketing'), ('authentication', 'Authentication')], max_length=20)),
                ('parameter_format', models.CharField(choices=[('named', 'Named'), ('positional', 'Positional')], default='named', max_length=20)),
                ('meta_template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('APPEAL_REQUESTED', 'Appeal Requested')], default='PENDING', max_length=30)),
                ('quality_rating', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PENDING', 'Quality Pending'), ('HIGH', 'High Quality'), ('MEDIUM', 'Medium Quality'), ('LOW', 'Low Quality')], default='UNKNOWN', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ttl_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('param_type', models.CharField(choices=[('text', 'Text'), ('currency', 'Currency'), ('date_time', 'Date Time')], default='text', max_length=20)),
                ('example_value', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='crm.templatecomponent')),
            ],
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='crm.whatsapptemplate'),
        ),
    ]
