# Generated by Django 6.0.3 on 2026-04-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_templatecomponent_whatsapptemplate_templateparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quick_reply', 'Quick Reply'), ('url', 'URL'), ('phone_number', 'Phone Number')], max_length=20)),
                ('text', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='crm.templatecomponent')),
            ],
        ),
    ]
