# Generated by Django 6.0.3 on 2026-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_templatebutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='language',
            field=models.CharField(choices=[('pt_BR', 'Portuguese (Brazil)'), ('en_US', 'English (United States)')], default='pt_BR', max_length=10),
        ),
    ]
