# Generated by Django 6.0.3 on 2026-04-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_whatsapptemplate_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('meta_template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crm.whatsapptemplate')),
            ],
        ),
    ]
