# Generated by Django 6.0.3 on 2026-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_messagecategory_categoryexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecategory',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Cor para exibição na interface (formato hexadecimal)', max_length=7),
        ),
        migrations.AlterField(
            model_name='messagecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da categoria para ajudar na compreensão'),
        ),
    ]
