# Generated by Django 6.0.3 on 2026-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_messagecategory_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryexample',
            options={},
        ),
        migrations.AddField(
            model_name='categoryexample',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
