# Generated by Django 6.0.3 on 2026-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_categoryexample_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryexample',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='categoryexample',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoryexample',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagecategory',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AlterField(
            model_name='messagecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
