# Generated by Django 6.0.3 on 2026-04-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_chat_created_at_contactwhatsapp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(related_name='dispatches', to='crm.contactwhatsapp')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='crm.whatsapptemplate')),
            ],
        ),
    ]