# Generated by Django 6.0.3 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]