# Generated by Django 6.0.3 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_dispatch_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundwhatsappmessage',
            name='with_template',
            field=models.BooleanField(default=False),
        ),
    ]