# Generated by Django 6.0.3 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_outboundwhatsappmessage_with_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnumber',
            name='language',
            field=models.CharField(choices=[('pt_BR', 'Portuguese (Brazil)'), ('en_US', 'English (United States)')], default='pt_BR', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]