# Generated by Django 6.0.3 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_whatsappnumber_language_pin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_ad_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_ban_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_ban_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_owner_business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_update_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='account_violation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='auth_international_rate_eligibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='volume_tier_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='waba_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]