# Generated by Django 6.0.3 on 2026-03-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_superadmininvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmininvite',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
