# Generated by Django 6.0.3 on 2026-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_superadmininvite_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmininvite',
            name='token',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
